# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HamraheManTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HamraheManTest

   # Networking
    pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift', :branch => 'develop'
    pod 'Alamofire', '~> 4.7'

    #UI
    pod 'Parchment'

    


  target 'HamraheManTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HamraheManTestUITests' do
    # Pods for testing
  end

end
